# Libraries and data

In [1]:
## Libraries 
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt

### Warning 
import warnings
warnings.filterwarnings("ignore")

# WITHOUT SPLINES PRE PROCESSING

In [2]:
## Data
data = pd.read_excel("./Base_PBM_Facteurs_Confusion.xlsx")
### Data cleaning 
data["transfusion CG"][np.where(data["transfusion CG"] > 0)[0]] = 1
data.dropna(inplace=True)
data.set_index(np.arange(len(data)))
print(len(data))
data.head()

435

,age,poids,taille,imc,redux,hta,diabete,avk,aod,plavix,...,betabloquant,diuretiques,hb,ferritinemie,coeff de sat,type intervention,duree rea,fibrinogene,Fibrinogène rdb,transfusion CG
0,69.0,68.0,1.63,25.593,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,14.6,56.0,14.0,1,1.0,3.64,2.27,0.0
1,65.0,71.0,1.72,23.999,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,14.0,199.0,20.0,2,2.0,1.91,1.30,0.0
2,79.0,79.0,1.60,30.859,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,12.9,51.0,26.0,5,2.0,3.57,2.43,1.0
3,80.0,69.0,1.69,24.158,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,14.6,387.0,21.0,1,1.0,2.43,1.78,0.0
4,72.0,80.0,1.70,27.681,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,11.6,24.0,6.0,5,2.0,4.15,3.23,1.0

In [8]:
data.describe()

,age,poids,taille,imc,redux,hta,diabete,avk,aod,plavix,...,autres aap,betabloquant,diuretiques,hb,ferritinemie,coeff de sat,duree rea,fibrinogene,Fibrinogène rdb,transfusion CG
count,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,...,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.00000
mean,68.011494,77.536782,2.030575,27.086400,0.062069,0.652874,0.213793,0.085057,0.103448,0.085057,...,0.013793,0.508046,0.344828,13.956322,189.662069,21.439080,3.328736,3.172828,2.133080,0.36092
std,10.250204,15.539967,7.111554,4.557788,0.241559,0.476605,0.410455,0.279288,0.304894,0.279288,...,0.116766,0.500511,0.475859,1.413016,163.805207,7.412646,2.883287,0.760864,0.614638,0.48082
min,22.000000,45.000000,1.470000,19.077000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,8.100000,7.000000,3.000000,1.000000,1.700000,0.850000,0.00000
25%,64.000000,67.000000,1.625000,23.735500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,13.000000,73.000000,16.000000,2.000000,2.655000,1.740000,0.00000
50%,70.000000,77.000000,1.700000,26.346000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,13.900000,140.000000,21.000000,2.000000,3.070000,2.030000,0.00000
75%,75.000000,86.000000,1.750000,29.408500,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,14.900000,258.000000,26.000000,4.000000,3.620000,2.430000,1.00000
max,84.000000,153.000000,150.000000,49.950000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,18.700000,962.000000,48.000000,35.000000,7.080000,4.700000,1.00000

In [3]:
print(data.columns)
len(data.columns)

Index(['age', 'poids', 'taille', 'imc', 'redux', 'hta', 'diabete', 'avk',
       'aod', 'plavix', 'kardegic', 'autres aap', 'betabloquant',
       'diuretiques', 'hb', 'ferritinemie', 'coeff de sat',
       'type intervention', 'duree rea', 'fibrinogene', 'Fibrinogène rdb',
       'transfusion CG'],
      dtype='object')

22

# Facteurs de confusion

In [4]:
Facteurs_Confusion = data.copy()

In [5]:
## Supp no-needed columns
del Facteurs_Confusion['fibrinogene']
del Facteurs_Confusion['transfusion CG']
X = Facteurs_Confusion 
y = data["transfusion CG"]
## Model 
from sklearn.linear_model import LogisticRegression
logitS = LogisticRegression()

In [6]:
Facteurs_Confusion.columns

Index(['age', 'poids', 'taille', 'imc', 'redux', 'hta', 'diabete', 'avk',
       'aod', 'plavix', 'kardegic', 'autres aap', 'betabloquant',
       'diuretiques', 'hb', 'ferritinemie', 'coeff de sat',
       'type intervention', 'duree rea', 'Fibrinogène rdb'],
      dtype='object')

### Librairie 1

In [9]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

In [10]:
## Backward 
# Sequential Backward Selection AVEC R2
sbs = SFS(logitS, 
          forward=False, 
          floating=False, 
          scoring='r2' )
sbs = sbs.fit(X, y)

print('\nSequential Backward Selection :')
print(sbs.k_feature_idx_)
print('CV Score:')
print(sbs.k_score_)
print(sbs.k_feature_names_)

Sequential Backward Selection :
(14,)
CV Score:
-0.1464992668621697
('hb',)

In [11]:
#sbs.subsets_

In [12]:
## Backward 
# Sequential Backward Selection AVEC NEG MEAN SQUARED ERROR
sbs = SFS(logitS, 
          forward=False,
          scoring='neg_mean_squared_error' )
sbs = sbs.fit(X, y)

print('\nSequential Backward Selection :')
print(sbs.k_feature_idx_)
print('CV Score:')
print(sbs.k_score_)
print(sbs.k_feature_names_)

Sequential Backward Selection :
(14,)
CV Score:
-0.26436781609195403
('hb',)

In [13]:
## Backward 
# Sequential Backward Selection AVEC ACCURACY
sbs = SFS(logitS, 
          forward=False,
          scoring='accuracy' )
sbs = sbs.fit(X, y)

print('\nSequential Backward Selection :')
print(sbs.k_feature_idx_)
print('CV Score:')
print(sbs.k_score_)
print(sbs.k_feature_names_)

Sequential Backward Selection :
(14,)
CV Score:
0.7356321839080461
('hb',)

In [14]:
## Forward
# Sequential Forward Selection AVEC R2
sbs = SFS(logitS,
          scoring='r2' )
sbs = sbs.fit(X, y)

print('\nSequential Backward Selection :')
print(sbs.k_feature_idx_)
print('CV Score:')
print(sbs.k_score_)
print(sbs.k_feature_names_)

Sequential Backward Selection :
(14,)
CV Score:
-0.1464992668621697
('hb',)

In [15]:
### STEPWISE
sbs = SFS(logitS,
          floating=True,
          scoring='r2' )
sbs = sbs.fit(X, y)

print('\nSequential Backward Selection :')
print(sbs.k_feature_idx_)
print('CV Score:')
print(sbs.k_score_)
print(sbs.k_feature_names_)

Sequential Backward Selection :
(14,)
CV Score:
-0.1464992668621697
('hb',)

### Librairie 2 : sklearn

https://scikit-learn.org/stable/modules/feature_selection.html
    
L1-based feature selection
Linear models penalized with the L1 norm have sparse solutions: many of their estimated coefficients are zero. When the goal is to reduce the dimensionality of the data to use with another classifier, they can be used along with feature_selection.SelectFromModel to select the non-zero coefficients. In particular, sparse estimators useful for this purpose are the linear_model.Lasso for regression, and of linear_model.LogisticRegression and svm.LinearSVC for classification.

In [16]:
from sklearn.feature_selection import SelectFromModel
logitS = LogisticRegression().fit(X,y)
model = SelectFromModel(logitS, prefit=True)
X_new = model.transform(X)

In [17]:
X_new.shape

(435, 10)

In [18]:
feature_names = np.array(X.columns)
print("Features selected by SelectFromModel: "
      f"{feature_names[model.get_support()]}")

Features selected by SelectFromModel: ['taille' 'redux' 'hta' 'diabete' 'aod' 'kardegic' 'betabloquant' 'hb'
 'type intervention' 'duree rea']

### Solution 3 avec Statmodel

In [19]:
import statsmodels.api as sm

In [20]:
#Adding constant column of ones, mandatory for sm.OLS model
X_1 = sm.add_constant(X)
#Fitting sm.OLS model
model = sm.OLS(y.astype(float),X_1.astype(float)).fit()
model.pvalues

const                6.389022e-06
age                  1.109612e-01
poids                1.047891e-04
taille               3.028241e-01
imc                  2.782755e-02
redux                3.600893e-02
hta                  6.912076e-01
diabete              2.984891e-01
avk                  3.509779e-01
aod                  7.486443e-02
plavix               7.828665e-01
kardegic             8.848174e-02
autres aap           1.587120e-01
betabloquant         4.150207e-01
diuretiques          5.795170e-01
hb                   6.942440e-08
ferritinemie         7.080229e-01
coeff de sat         6.945769e-01
type intervention    3.690669e-05
duree rea            2.768002e-06
Fibrinogène rdb      5.311686e-01
dtype: float64

In [21]:
#Backward Elimination
cols = list(X.columns)
pmax = 1
while (len(cols)>0):
    p=[]
    X_1 = X[cols]
    X_1 = sm.add_constant(X_1)
    model = sm.OLS(y.astype(float),X_1.astype(float)).fit()
    p = pd.Series(model.pvalues.values[1:],index = cols)      
    pmax = max(p)
    feature_with_p_max = p.idxmax()
    if(pmax>0.05):
        cols.remove(feature_with_p_max)
    else:
        break
selected_features_BE = cols
print(selected_features_BE)

['poids', 'imc', 'kardegic', 'hb', 'type intervention', 'duree rea']

# WITH SPLINE

In [22]:
from patsy import dmatrix 
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [23]:
## Cubic spline (B_Spline) process on fibrinogene rdb
transformed_fibri = dmatrix("bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)", {"train": data['Fibrinogène rdb']},return_type='dataframe')
Facteurs_Confusion_Spline = pd.concat([data.copy(),transformed_fibri], axis = 1)

In [24]:
transformed_fibri.head()

,Intercept,"bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[0]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[1]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[2]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[3]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[4]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[5]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[6]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[7]"
0,1.0,0.000000,0.014748,0.455273,0.503735,0.026244,0.000000,0.00000,0.0
1,1.0,0.451714,0.445273,0.073883,0.000000,0.000000,0.000000,0.00000,0.0
2,1.0,0.000000,0.000416,0.245136,0.648439,0.106009,0.000000,0.00000,0.0
3,1.0,0.016103,0.399282,0.555345,0.029269,0.000000,0.000000,0.00000,0.0
4,1.0,0.000000,0.000000,0.000000,0.026244,0.648732,0.316604,0.00842,0.0

In [25]:
## Supp no-needed columns
del Facteurs_Confusion_Spline['fibrinogene']
del Facteurs_Confusion_Spline['transfusion CG']
del Facteurs_Confusion_Spline['Fibrinogène rdb']
del Facteurs_Confusion_Spline['Intercept']
X = Facteurs_Confusion_Spline
y = data["transfusion CG"]
## Model 
from sklearn.linear_model import LogisticRegression
logitS = LogisticRegression()

In [26]:
Facteurs_Confusion_Spline.columns

Index(['age', 'poids', 'taille', 'imc', 'redux', 'hta', 'diabete', 'avk',
       'aod', 'plavix', 'kardegic', 'autres aap', 'betabloquant',
       'diuretiques', 'hb', 'ferritinemie', 'coeff de sat',
       'type intervention', 'duree rea',
       'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[0]',
       'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[1]',
       'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[2]',
       'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[3]',
       'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[4]',
       'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[5]',
       'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[6]',
       'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[7]'],
      dtype='object')

### sklearn

In [27]:
from sklearn.feature_selection import SelectFromModel
logitS = LogisticRegression().fit(X,y)
model = SelectFromModel(logitS, prefit=True)
X_new = model.transform(X)

In [28]:
feature_names = np.array(X.columns)
print("Features selected by SelectFromModel: "
      f"{feature_names[model.get_support()]}")

Features selected by SelectFromModel: ['taille' 'redux' 'hta' 'diabete' 'aod' 'kardegic' 'betabloquant' 'hb'
 'type intervention' 'duree rea'
 'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[0]'
 'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[2]'
 'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[3]']

### statmodel

In [29]:
#Adding constant column of ones, mandatory for sm.OLS model
X_1 = sm.add_constant(X)
#Fitting sm.OLS model
model = sm.OLS(y.astype(float),X_1.astype(float)).fit()
model.pvalues

const                                                                           1.487690e-05
age                                                                             5.317453e-02
poids                                                                           5.939046e-04
taille                                                                          2.326816e-01
imc                                                                             4.936489e-02
redux                                                                           2.281834e-02
hta                                                                             7.085007e-01
diabete                                                                         1.849139e-01
avk                                                                             3.684665e-01
aod                                                                             4.653959e-02
plavix                                                                          8.328950e-01
kardegic                                                                        1.867912e-01
autres aap                                                                      1.775597e-01
betabloquant                                                                    8.965890e-01
diuretiques                                                                     5.368043e-01
hb                                                                              3.605043e-07
ferritinemie                                                                    9.193921e-01
coeff de sat                                                                    6.241750e-01
type intervention                                                               1.912651e-05
duree rea                                                                       9.879021e-07
bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[0]    8.232582e-01
bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[1]    9.132610e-02
bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[2]    5.371872e-02
bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[3]    1.343801e-01
bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[4]    6.061076e-02
bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[5]    5.099572e-01
bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[6]    4.766776e-01
bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[7]    7.341532e-01
dtype: float64

In [30]:
#Backward Elimination
cols = list(X.columns)
pmax = 1
while (len(cols)>0):
    p=[]
    X_1 = X[cols]
    X_1 = sm.add_constant(X_1)
    model = sm.OLS(y.astype(float),X_1.astype(float)).fit()
    p = pd.Series(model.pvalues.values[1:],index = cols)      
    pmax = max(p)
    feature_with_p_max = p.idxmax()
    if(pmax>0.05):
        cols.remove(feature_with_p_max)
    else:
        break
selected_features_BE = cols
print(selected_features_BE)

['poids', 'imc', 'kardegic', 'hb', 'type intervention', 'duree rea', 'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[2]', 'bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[4]']

# We do the same on R with AIC and BIC selection

### Save Facteurs de Confusion with fibrinogene transform into spline

In [31]:
Facteurs_Confusion_Spline[:-1]

,age,poids,taille,imc,redux,hta,diabete,avk,aod,plavix,...,type intervention,duree rea,"bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[0]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[1]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[2]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[3]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[4]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[5]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[6]","bs(train, knots=(1.5, 2, 2.5, 3, 3.5), degree=3, include_intercept=False)[7]"
0,69.0,68.0,1.63,25.593,0.0,1.0,0.0,0.0,0.0,0.0,...,1,1.0,0.000000,0.014748,0.455273,0.503735,0.026244,0.000000,0.00000,0.0
1,65.0,71.0,1.72,23.999,0.0,0.0,0.0,0.0,0.0,1.0,...,2,2.0,0.451714,0.445273,0.073883,0.000000,0.000000,0.000000,0.00000,0.0
2,79.0,79.0,1.60,30.859,0.0,0.0,0.0,1.0,0.0,1.0,...,5,2.0,0.000000,0.000416,0.245136,0.648439,0.106009,0.000000,0.00000,0.0
3,80.0,69.0,1.69,24.158,0.0,1.0,0.0,0.0,0.0,1.0,...,1,1.0,0.016103,0.399282,0.555345,0.029269,0.000000,0.000000,0.00000,0.0
4,72.0,80.0,1.70,27.681,0.0,1.0,0.0,1.0,0.0,0.0,...,5,2.0,0.000000,0.000000,0.000000,0.026244,0.648732,0.316604,0.00842,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,68.0,82.0,1.78,25.880,0.0,1.0,0.0,0.0,0.0,0.0,...,2,5.0,0.049555,0.504795,0.437875,0.007776,0.000000,0.000000,0.00000,0.0
468,78.0,54.0,1.63,20.324,0.0,1.0,0.0,0.0,0.0,0.0,...,2,4.0,0.277192,0.563365,0.158194,0.000000,0.000000,0.000000,0.00000,0.0
470,82.0,67.0,1.60,26.171,1.0,0.0,0.0,0.0,0.0,0.0,...,1,4.0,0.000000,0.103253,0.663456,0.233003,0.000288,0.000000,0.00000,0.0
471,72.0,82.0,1.70,28.373,0.0,1.0,0.0,0.0,0.0,1.0,...,2,2.0,0.120237,0.578195,0.301111,0.000457,0.000000,0.000000,0.00000,0.0
473,69.0,90.0,1.68,31.887,0.0,1.0,1.0,0.0,0.0,0.0,...,1,3.0,0.000002,0.160784,0.682349,0.156865,0.000000,0.000000,0.00000,0.0

In [32]:
Facteurs_Confusion_Spline.to_excel("Facteurs_Confusion_Spline.xlsx")